### ISSUE TITLE
Qurl looks to be non-functional

### ISSUE THREAD

**Issue by rwhitworth** [p5-shorten/www-shorten-qurl#1]
The Qurl website no longer looks to be functional.  The tests included with the distribution do not work due to missing the email field as part of the required API call.  However, manual testing of the API do not work either, hinting that the website is no longer functional.  I emailed the administrators of the website using the contact form on their website and have received no response in 6 days.

It may be time to retire this module.

**Comment by genio** [comment]
After quite a bit of trying, it seems you are right. Closed with release 2.011
